const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';
const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_FAILED = 'SIGNUP_FAILED';
const GET_OTP = 'GET_OTP';
const OTP_REQUEST_SUCCESS = 'OTP_REQUEST_SUCCESS';
const OTP_REQUEST_FAILED = 'OTP_REQUEST_FAILED';
const SHOW_LOADING = 'SHOW_LOADING';
const LOGIN_SUCCESSS = 'LOGIN_SUCCESSS';
const USER_TOKEN = 'USER_TOKEN';
const RESEND_OTP = 'RESEND_OTP';
const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
const RESND_OTP_FAILED = "RESND_OTP_FAILED"
const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

export {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  SIGNUP_REQUEST,
  SIGNUP_SUCCESS,
  SIGNUP_FAILED,
  GET_OTP,
  OTP_REQUEST_SUCCESS,
  OTP_REQUEST_FAILED,
  SHOW_LOADING,
  LOGIN_SUCCESSS,
  USER_TOKEN,
  RESEND_OTP,
  RESEND_OTP_SUCCESS,
  RESND_OTP_FAILED,
  FORGOT_PASSWORD_REQUEST,
  FORGOT_PASSWORD_SUCCESS,
  FORGOT_PASSWORD_FAILED,
};
