const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_FAILED = 'LOGIN_FAILED';
const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_FAILED = 'SIGNUP_FAILED';
const GET_OTP = 'GET_OTP'; ///// Checked
const OTP_REQUEST_SUCCESS = 'OTP_REQUEST_SUCCESS';
const OTP_REQUEST_FAILED = 'OTP_REQUEST_FAILED';
const SHOW_LOADING = 'SHOW_LOADING';
const LOGIN_SUCCESSS = 'LOGIN_SUCCESSS';
const USER_TOKEN = 'USER_TOKEN';
const RESEND_OTP = 'RESEND_OTP';
const RESEND_OTP_SUCCESS = 'RESEND_OTP_SUCCESS';
const RESND_OTP_FAILED = 'RESND_OTP_FAILED';
const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
const FORGOT_PASSWORD_STATUS = 'FORGOT_PASSWORD_STATUS';
const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';
const LOGIN_REQUEST_MOBILE = 'LOGIN_REQUEST_MOBILE'; //// checked
const SIGNUP_REQUEST_MOBILE = 'SIGNUP_REQUEST_MOBILE'; /// checked
const LOGIN_REQUEST_MOBILE_STATUS = 'LOGIN_REQUEST_MOBILE_STATUS'; //// checked   ---- done
const OTP_REQUEST_STATUS = 'OTP_REQUEST_STATUS'; ////checked
const RESTE_OTP_RESPONSE = 'RESTE_OTP_RESPONSE'; /// checked
const LOGIN_STATUS = 'LOGIN_STATUS';
const GET_OTP_FORGET = 'GET_OTP_FORGET'; /// checked
const FORGET_OTP_REQUEST_STATUS = 'FORGET_OTP_REQUEST_STATUS'; ////checked
const FORGET_VIA_OTP = 'FORGET_VIA_OTP'; //// checked
const FORGET_VIA_OTP_STATUS = 'FORGET_VIA_OTP_STATUS'; /// checked

export {
  FORGET_VIA_OTP_STATUS, /// checked
  FORGET_VIA_OTP, //// checked
  FORGET_OTP_REQUEST_STATUS, //// checked
  GET_OTP_FORGET, //// checked
  LOGIN_STATUS, ////  cheked
  RESTE_OTP_RESPONSE, /// checked
  OTP_REQUEST_STATUS, //// checked
  LOGIN_REQUEST_MOBILE_STATUS, //// checked   ---- done
  SIGNUP_REQUEST_MOBILE,
  LOGIN_REQUEST_MOBILE, /// checked
  LOGIN_REQUEST,
  LOGIN_FAILED,
  SIGNUP_REQUEST,
  SIGNUP_SUCCESS,
  SIGNUP_FAILED,
  GET_OTP, /////checked
  OTP_REQUEST_SUCCESS,
  OTP_REQUEST_FAILED,
  SHOW_LOADING,
  LOGIN_SUCCESSS,
  USER_TOKEN,
  RESEND_OTP,
  RESEND_OTP_SUCCESS,
  RESND_OTP_FAILED,
  FORGOT_PASSWORD_REQUEST,
  FORGOT_PASSWORD_STATUS,
  FORGOT_PASSWORD_FAILED,
};
