const LOGIN_REQUEST = 'LOGIN_REQUEST';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';
const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
const SIGNUP_FAILED = 'SIGNUP_FAILED';
const GET_OTP = 'GET_OTP';
const OTP_REQUEST_SUCCESS = 'OTP_REQUEST_SUCCESS';
const OTP_REQUEST_FAILED = 'OTP_REQUEST_FAILED';
const SHOW_LOADING = 'SHOW_LOADING';
const LOGIN_SUCCESSS = 'LOGIN_SUCCESSS';
const USER_TOKEN = 'USER_TOKEN';

export {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  SIGNUP_REQUEST,
  SIGNUP_SUCCESS,
  SIGNUP_FAILED,
  GET_OTP,
  OTP_REQUEST_SUCCESS,
  OTP_REQUEST_FAILED,
  SHOW_LOADING,
  LOGIN_SUCCESSS,
  USER_TOKEN,
};
